### ISSUE TITLE
ROS2 version

### ISSUE THREAD

**Issue by kentoshima** [TempleRAIL/pedsim_ros_with_gazebo#1]
Is there a ROS2 version of this is under developing?

If not, could someone tell me which modifications need to be made in order to run this in ROS2 Humble?

**Comment by zzuxzt** [comment]
Not yet, I am busy with other projects. But if you really plan to use this package in ROS2, you can try to use  [ros1_brigde](https://github.com/ros2/ros1_bridge) package to bridge this ROS1 package to ROS2.
