### ISSUE TITLE
Something I can not understand，Please your reply～

### ISSUE THREAD

**Issue by Denghaoyuan123** [TempleRAIL/pedsim_ros_with_gazebo#2]
1. Do I need to write the.xml under /src/pedsim_ros_with_gazebo/pedsim_simulator/scenarios folder manually? If I want to add my own world to test the algorithm?
Is the.xml file written yourself, or is it automatically generated by some method?

2. If I want to define my own world, do I need to put the.xml file in the corresponding location before running sh run_drl_vo_policy_training_desktop.sh ~/drl_vo_runs? Then the program will automatically generate the corresponding.world and.launch files and call them？

**Comment by zzuxzt** [comment]
1. Yes, you need to create the *.xml by yourself manually. 
2. You also need to generate the *.world Gazebo file by following this [pedsim_gazebo_plugin](https://github.com/TempleRAIL/pedsim_ros_with_gazebo/tree/drl_vo/pedsim_gazebo_plugin) with your *.xml file. Then modify the [drl_vo_nav_train.launch](https://github.com/TempleRAIL/drl_vo_nav/blob/baa970c30cabe94a8b0eb81bb0ad0b97261f2458/drl_vo/launch/drl_vo_nav_train.launch#L2C1-L3C88) with your world files.
```
<arg name="scene_file" default="$(find pedsim_simulator)/scenarios/your_world.xml"/>
<arg name="world_name" default="$(find pedsim_gazebo_plugin)/worlds/your_world.world"/>
```

**Comment by Denghaoyuan123** [comment]
thanks, I will try it. Have a good day!
