### ISSUE TITLE
The pedestrian 3D model not spawn

### ISSUE THREAD

**Issue by daleigehhh** [TempleRAIL/pedsim_ros_with_gazebo#5]
Hi, @zzuxzt 
I compiled these packages and launch the simulator successfully. But no pedestrian model spawned, I noticed that the ros logger were logging the spawning of the agents without any problem, but no agent ever appear in gazebo, I think maybe it is because I do not have the 3D model of the avatar.

**Comment by zzuxzt** [comment]
This happens when Gazebo is not completely shut down. Did you try to restart the simulation? Restarting can solve most spawning issues. A 3D model of a pedestrian is already included in this package.

Can you see the pedestrian visualization in Rviz? If not, you may launch an empty Gazebo world without pedestrians.

**Comment by daleigehhh** [comment]
I read the pedsim_ros code and now I am debugging your code. The visualizer does not appear at all though the launch log said it has been launched successfully, it is weird. The agents spawning phase persists about 5 minutes during launching the eng_hall.xml config and eng_hall.world which is the default option and there is still no pedestrian in the world, besides the gzclient kept inactive during the spawning phase. Here are the whole launching logs. I think the problem maybe happened when spawning the Turtlebot2 base, there were two warnings about the parameters of Kobuki: 
1. the Kobuki base does not have RosDebugLevel
2. the Kobuki base does not have update rate and default to 0
![frag3](https://github.com/user-attachments/assets/586bd26e-547c-4665-8f2d-52e6b95adc47)

![frag1](https://github.com/user-attachments/assets/8998f54a-2b82-4484-a020-6ca8635584ba)
![frag2](https://github.com/user-attachments/assets/eda2b88f-d5d2-4101-97c6-c680646f7aa2)

**Comment by daleigehhh** [comment]
In rviz, there is an error about loading the urdf of the kobuki base_link, the pedestrians shows normally but in gazebo there is only the robot. 
![Uploading rviz.png…]()
![Uploading gazebo.png…]()

**Comment by daleigehhh** [comment]
The rviz goes like this,  the robot spawner has no problem. And it seems the wrapped pedsim_ros works as well, I can see the social forces. 
![rviz](https://github.com/user-attachments/assets/84712870-1a3d-4428-83a4-24b2bba4ad29)
![rviz2](https://github.com/user-attachments/assets/fe345a98-93cc-47e7-8289-c4c7885e9c8d)

**Comment by zzuxzt** [comment]
You also need to get our [robot_gazebo](https://github.com/TempleRAIL/robot_gazebo) package to load the Turtlebot2 robot. The detailed usage of our simulator can be found in our [drl_vo_nav](https://github.com/TempleRAIL/drl_vo_nav) package.  You can do this and run the simulation by following these steps:
```
cd ~/catkin_ws/src
git clone https://github.com/TempleRAIL/robot_gazebo.git
git clone https://github.com/TempleRAIL/pedsim_ros_with_gazebo.git
cd ..
catkin_make
source ~/catkin_ws/devel/setup.sh

roslaunch pedsim_simulator robot.launch
roslaunch robot_gazebo view_navigation.launch
```
By the way, did you install all the packages for the Turtlebot2? If not, please install them following our [drl_vo_nav](https://github.com/TempleRAIL/drl_vo_nav) package. 

A GPU is required to make the simulator run fast (especially with our default setting of 34 pedestrians).

PS: If you have trouble configuring your environment, you can also test our simulator using our Singularity container: ["drl_vo_container.sif"](https://doi.org/10.5281/zenodo.7679658).
